apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xwaxth8ax-python-gitops
  description: This is GitOps manifest for xwaxth8ax-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=xwaxth8ax-python
    backstage.io/kubernetes-id: xwaxth8ax-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xwaxth8ax-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xwaxth8ax-python
